apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: monitoring
spec:
  ports:
    - name: web-ui
      port: 9000
      targetPort: 9000
    - name: gelf
      port: 12201
      targetPort: 12201
    - name: syslog
      port: 1514
      targetPort: 1514
  selector:
    app: graylog