apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: monitoring
spec:
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 9000
    - port: 12201
      targetPort: 12201
      nodePort: 12201
    - port: 1514
      targetPort: 1514
      nodePort: 1514
  selector:
    app: graylog