include:
  - ./rabbitmq/compose.yml
  - ./kafka/compose.yml
  - ./pg-identity/compose.yml
  - ./pg-workspace/compose.yml
  - ./pg-project/compose.yml
  - ./vault/compose.yml
  - ./minio/compose.yml
  - ./jaeger/compose.yml
  - ./graylog/compose.yml

networks:
  api_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/16
  data_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.70.0.0/16
  monitoring_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16
