services:
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "${JAEGER_UI_PORT}:16686"
      - "${JAEGER_PORT}:6831/udp"
      - "${JAEGER_ZIPKIN_PORT}:5775/udp"
      - "${JAEGER_COMPACT_THRIFT_PORT}:6831/udp"
      - "${JAEGER_BINARY_THRIFT_PORT}:6832/udp"
      - "${JAEGER_AGENT_SERVE_PORT}:5778"
      - "${JAEGER_COLLECTOR_HTTP_PORT}:14268"
      - "${JAEGER_COLLECTOR_GRPC_PORT}:14250"
      - "${COLLECTOR_ZIPKIN_HTTP_PORT}:9411" 
    networks:
      - monitoring_network
      - data_network
    depends_on:
      - elasticsearch
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=${COLLECTOR_ZIPKIN_HTTP_PORT}
      - SPAN_STORAGE_TYPE=${SPAN_STORAGE_TYPE}
      - ES_SERVER_URLS=${ES_SERVER_URLS}
      - ES_USERNAME=${ELASTIC_USERNAME:-}
      - ES_PASSWORD=${ELASTIC_PASSWORD:-}
      - QUERY_BASE_PATH=${QUERY_BASE_PATH}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s