apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: hashicorp/consul:latest
          args: ["agent", "-dev", "-client=0.0.0.0"]
          ports:
            - containerPort: 8500
