apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: secrets
spec:
  type: NodePort
  selector:
    app: consul
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
      nodePort: 32000
