apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/jaeger:2.5.0
        ports:
        - containerPort: 16686
        - containerPort: 6831
        - containerPort: 5775
        - containerPort: 6832
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        volumeMounts:
        - name: jaeger-storage
          mountPath: /tmp/jaeger
      volumes:
        - name: jaeger-storage
          emptyDir: {}