apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
      nodePort: 31120
    - name: jaeger-udp-compact
      port: 6831
      targetPort: 6831
      nodePort: 31121
      protocol: UDP
    - name: jaeger-udp-binary
      port: 5775
      targetPort: 5775
      nodePort: 31122
      protocol: UDP
    - name: jaeger-udp-compact-tcp
      port: 6832
      targetPort: 6832
      nodePort: 31123
      protocol: UDP
    - name: jaeger-http-collector
      port: 14268
      targetPort: 14268
      nodePort: 31124
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
      nodePort: 31125
    - name: zipkin
      port: 9411
      targetPort: 9411
      nodePort: 31126
  selector:
    app: jaeger