apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
    - name: jaeger-udp-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: jaeger-udp-binary
      port: 5775
      targetPort: 5775
      protocol: UDP
    - name: jaeger-udp-compact-tcp
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: jaeger-http-collector
      port: 14268
      targetPort: 14268
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
    - name: zipkin
      port: 9411
      targetPort: 9411
  selector:
    app: jaeger