version: '3.8'

services:
  project-db:
    image: postgres:latest
    container_name: project-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c hba_file=/custom_pg_hba.conf
    volumes:
      - postgres_project_data:/var/lib/postgresql/data
      - ./custom_pg_hba.conf:/custom_pg_hba.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_project_data: