apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  ports:
    - name: api
      port: 5672
      targetPort: 5672
    - name: management-ui
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq