apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-container
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-container
  template:
    metadata:
      labels:
        app: kafka-container
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:9092,EXTERNAL://localhost:29092"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_UI_PORT
              value: "8090"
            - name: KAFKA_UI_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_UI_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper:2181"
            - name: KAFKA_UI_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc