apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: messaging
spec:
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 9092
    - port: 29092
      targetPort: 29092
      nodePort: 29092
  selector:
    app: kafka