apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: messaging
spec:
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
    - name: kafka-external
      port: 29092
      targetPort: 29092
  selector:
    app: kafka