apiVersion: v1
kind: Service
metadata:
  name: kafka-container
  namespace: messaging
spec:
  type: NodePort
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
    - name: kafka-external
      port: 29092
      targetPort: 29092
      nodePort: 30120
  selector:
    app: kafka-container