version: '3.8'

services:
  graylog:
    image: graylog/graylog:4.3
    expose:
      - ${GRAYLOG_WEB_PORT}
      - ${GRAYLOG_GELF_PORT}
    ports:
      - "${GRAYLOG_WEB_PORT}:9000"
      - "${GRAYLOG_GELF_PORT}:12201/udp"
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOST}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI}
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    depends_on:
      - elasticsearch
      - mongodb
    restart: "on-failure"
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    restart: "on-failure"
  
  mongodb:
    image: mongo:4.4
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

volumes:
  mongodb_data:
  es_data:
  graylog_data:
  graylog_journal: