apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        ports:
          - containerPort: 8525
        env:
          - name: VAULT_ADDR
            value: "http://0.0.0.0:8525"
          - name: VAULT_LOCAL_CONFIG
            value: '{"ui":true,"api_addr":"http://0.0.0.0:8525","storage":{"consul":{"address":"consul:8500","path":"vault/"}},"listener":{"tcp":{"address":"0.0.0.0:8525","tls_disable":"true"}},"default_lease_ttl":"168h","max_lease_ttl":"720h"}'
          - name: VAULT_DEV_ROOT_TOKEN_ID
            valueFrom:
              secretKeyRef:
                name: vault-secrets
                key: VAULT_DEV_ROOT_TOKEN_ID
        volumeMounts:
          - mountPath: /data
            name: vault-data
        securityContext:
          capabilities:
            add:
              - IPC_LOCK