apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        ports:
          - containerPort: 9000
          - containerPort: 9001
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: MINIO_ROOT_USER
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: MINIO_ROOT_PASSWORD
          - name: MINIO_ENDPOINT
            value: "http://localhost:9001"
          - name: MINIO_IDENTITYSERVICE_BUCKET
            value: "identityservice"
          - name: MINIO_REGION
            value: "us-east-1"
        volumeMounts:
          - mountPath: /data
            name: minio-data