apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: storage
spec:
  ports:
    - name: api
      port: 9001
      targetPort: 9001
    - name: ui
      port: 9002
      targetPort: 9002
  selector:
    app: minio